services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - 6000:7000
    
